language: python
sudo: false

dist: xenial
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
services:
  - xvfb

env:
  global:
    - MPLBACKEND=TkAgg

matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      env:  COVERAGE=true
    - python: "3.8"

cache: pip

install:
  - pip install "numpy>=1.16"
  - pip install numina
  - pip install "scikit-image>=0.12" scikit-learn photutils
  - pip install sep lmfit
  - pip install pytest pytest-remotedata
  - pip install pytest-benchmark
  - |
    if [[ $COVERAGE == true ]]; then
      pip install codeclimate-test-reporter coveralls;
    fi

script:
  - |
    if [[ $COVERAGE == true ]]; then
      coverage run --source emirdrp -m pytest
    else
      py.test -s -v emirdrp
    fi

after_success:
  - if [[ $COVERAGE == true ]]; then coveralls; fi
  - if [[ $COVERAGE == true ]]; then codeclimate-test-reporter; fi
