language: python
sudo: false

env:
  global:
    - MPLBACKEND=TkAgg

matrix:
  include:
    - python: "2.7"
    - python: "3.5"
      env:  COVERAGE=true
    - python: "3.5"
    - python: "3.6"
    - python: "3.6"

cache: pip

install:
  - pip install "numpy>=1.16"
  - pip install numina
  - pip install "scikit-image>=0.12" scikit-learn photutils
  - pip install sep lmfit
  - pip install pytest
  - pip install pytest-benchmark pytest-cov
  - if [[ $COVERAGE == true ]]; then pip install coveralls; fi
  - if [[ $COVERAGE == true ]]; then pip install codeclimate-test-reporter; fi


before_script:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - py.test -s -v emirdrp
  - if [[ $COVERAGE == true ]]; then py.test emirdrp --cov=emirdrp; fi

after_success:
  - if [[ $COVERAGE == true ]]; then coveralls; fi
  - if [[ $COVERAGE == true ]]; then codeclimate-test-reporter; fi